taller/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tarea/', include('tarea.urls', namespace="tarea")),
]

tarea/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name ="clase_index"),
    url(r'^create/lista$', views.ListaCreateView.as_view(), name ="crear_lista"),
    url(r'^edit/(?P<pk>[0-9]+)$', views.ListaUpdateView.as_view(), name ="modificar_lista"),
    url(r'^(?P<pk>[0-9]+)$', views.DetailList.as_view(), name ="detalle_lista"),
    url(r'^eliminar/lista(?P<pk>[0-9]+)$', views.ListaDeleteView.as_view(), name ="eliminar_lista"),
    url(r'^tareas$', views.TareaIndexView.as_view(), name ="clase_tarea"),
    url(r'^create/tarea$', views.TareaCreateView.as_view(), name ="crear_tarea"),
    url(r'^edit/tarea(?P<pk>[0-9]+)$', views.TareaUpdateView.as_view(), name ="modificar_tarea"),
    url(r'^eliminar/tarea(?P<pk>[0-9]+)$', views.TareaDeleteView.as_view(), name ="eliminar_tarea"),
    url(r'^pendientes$', views.TareaPendiente.as_view(), name ="tareas_pendientes"),
    url(r'^terminadas$', views.TareaTerminadaMes.as_view(), name ="tareas_terminadas"),
    url(r'^pendiente/mes$', views.TareaPendienteMes.as_view(), name ="tareas_pendientes_mes"),
    url(r'^(?P<lista_id>[0-9]+)/finalizada$', views.terminarTarea, name ="marcar_tarea"),
    url(r'^(?P<lista_id>[0-9]+)/curso$', views.desmarcar, name ="desmarcar_tarea"),

]

tarea/models.py
from datetime import datetime
from django.utils import timezone
from django.db import models


# Create your models here.
class Lista(models.Model):
	titulo_lista = models.CharField(max_length=50)
	fecha_creacion_lista = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.titulo_lista


class Tarea(models.Model):
	lista = models.ForeignKey(Lista, null=True, on_delete=models.CASCADE)
	titulo_tarea = models.CharField(max_length=50)
	terminado =models.BooleanField(default=False)
	fecha_creacion_tarea = models.DateTimeField(auto_now_add=True)
	fecha_modificacion = models.DateTimeField(auto_now=True)
	descripcion = models.TextField(blank=True)

	def __str__(self):
		return self.titulo_tarea

	

tarea/forms.py
from django import forms
from . import models

class ListaForm(forms.ModelForm):

	class Meta:
		model = models.Lista
		fields = ['titulo_lista']

		labels = { 

			'titulo_lista': 'Titulo de la lista'
			}

		widgets = {
			'titulo_lista': forms.TextInput(attrs={'class': 'form-control'})
			}


class TareaForm(forms.ModelForm):

	class Meta:
		model = models.Tarea
		fields = ['lista', 'titulo_tarea','descripcion']


		widgets = {
			'lista': forms.Select(attrs={'class': 'form-control'}),
			'titulo_tarea': forms.TextInput(attrs={'class': 'form-control'}),
			'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
		}


	

tarea/views.py
import datetime
from datetime import datetime, timedelta
from datetime import date
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib import messages


from .models import Lista, Tarea
from .forms import ListaForm, TareaForm


class BaseView(object):
	
	def get_active_title(self):
		if self.active_title:
			return self.active_title

	def get_context_data(self):
		context = super(BaseView, self).get_context_data()
		context['active_title'] = self.get_active_title()
		return context


class IndexView(BaseView, generic.ListView):
	active_title = 'lista'
	model = Lista
	template_name = 'tarea/index.html'


class ListaCreateView(generic.CreateView):
	active_title = 'lista'
	model = Lista
	form_class = ListaForm
	template_name = 'tarea/lista_form.html'
	success_url =reverse_lazy('tarea:clase_index')


class ListaUpdateView(generic.UpdateView):
	active_title = 'lista'
	model = Lista
	form_class = ListaForm
	template_name = 'tarea/lista_form.html'
	success_url =reverse_lazy('tarea:clase_index') 



class DetailList(generic.DetailView):
	active_title = 'lista'
	model = Lista
	template_name = 'tarea/lista_detail.html'



class ListaDeleteView(generic.DeleteView):
	model = Lista
	template_name = 'tarea/lista_delete.html'
	success_url = reverse_lazy('tarea:clase_index')



class TareaIndexView(BaseView, generic.ListView):
	active_title = 'tarea'
	model = Tarea
	template_name = 'tarea/tarea_index.html'
		
	def get_queryset(self):
		queryset = Tarea.objects.filter(fecha_creacion_tarea__lte=timezone.now()).order_by('-fecha_creacion_tarea')
		return queryset



class TareaCreateView(generic.CreateView):
	model = Tarea
	form_class = TareaForm
	template_name = 'tarea/tarea_form.html'
	success_url = reverse_lazy('tarea:clase_tarea')


class TareaUpdateView(generic.UpdateView):
	model = Tarea
	form_class = TareaForm
	template_name = 'tarea/tarea_form.html'
	success_url = reverse_lazy('tarea:clase_tarea')



class TareaDeleteView(generic.DeleteView):
	model = Tarea
	template_name = 'tarea/tarea_delete.html'
	success_url = reverse_lazy('tarea:clase_tarea')


class TareaPendiente(generic.ListView):
	model = Tarea
	
	template_name = 'tarea/tareas_pendientes.html'
	def get_queryset(self):
		queryset = Tarea.objects.exclude(terminado=True)
		return queryset



class TareaTerminadaMes(generic.ListView):
	model = Tarea
	template_name = 'tarea/tareas_terminadas.html'

	def get_queryset(self):
		queryset = Tarea.objects.filter(fecha_modificacion__month=timezone.now().month, terminado=True)
		return queryset



class TareaPendienteMes(generic.ListView):
	model = Tarea
	template_name = 'tarea/tareas_pendientes_mes.html'

	def get_queryset(self):
		
		queryset = Tarea.objects.filter( fecha_creacion_tarea__lt= timezone.now() - timedelta(days=30), terminado=False )
		return queryset

def terminarTarea(request, lista_id):
	lista = get_object_or_404(Lista, pk= lista_id)
	try:
		id_tarea = request.GET.get('tarea', 0)
		tarea_marcada = lista.tarea_set.select_for_update().get(pk=id_tarea)
	except (KeyError, Tarea.DoesNotExist):
		message_text = "Error"
		messages.add_message(request, messages.ERROR, message_text)
		return render(request, 'tarea/lista_detail.html',  {
			'lista':lista,
			'error_message': message_text,

			})
	else:


		tarea_marcada.terminado= True
		tarea_marcada.save()
		message_text = "Tarea Finalizada"
		messages.add_message(request, messages.SUCCESS, message_text)
		return HttpResponseRedirect(reverse('tarea:detalle_lista', args=(lista.id,)))

def desmarcar(request, lista_id):
	lista = get_object_or_404(Lista, pk= lista_id)
	try:
		id_tarea = request.GET.get('tarea', 0)
		tarea_marcada = lista.tarea_set.select_for_update().get(pk=id_tarea)
	except (KeyError, Tarea.DoesNotExist):
		message_text = "Error"
		messages.add_message(request, messages.ERROR, message_text)
		return render(request, 'tarea/lista_detail.html',  {
			'lista':lista,
			'error_message': message_text,

			})
	else:
		if tarea_marcada.fecha_creacion_tarea >= timezone.now() - timedelta(days=30):
			tarea_marcada.terminado= False
			tarea_marcada.save()
			message_text = "Tarea Finalizada"
			messages.add_message(request, messages.SUCCESS, message_text)
			return HttpResponseRedirect(reverse('tarea:detalle_lista', args=(lista.id,)))
		else: 
			message_text = "No se puede desmarcar esta tarea"
			messages.add_message(request, messages.ERROR, message_text)
			return HttpResponseRedirect(reverse('tarea:detalle_lista', args=(lista.id,)))








	





	

tarea/templates/tarea/index.html
{% extends 'base.html' %}


{% block container %}

<div class= "container">
<a href="{% url 'tarea:crear_lista' %}" class="btn btn-default btn-lg btn-block">Crear Lista</a>

{% if object_list %}
	 
        {% for lista in object_list %}

        <div class="jumbotron">
  			<h2><a href="{% url 'tarea:detalle_lista' lista.id %}">{{ lista.titulo_lista }}</a> </h2>
  			<h5>{{ lista.fecha_creacion_lista }}</h5>
  			
  			<div class="d-inline">

  			<form method="post">
  			{% csrf_token %}

  			<a href="{% url 'tarea:modificar_lista' lista.id %}" class="btn btn-primary btn-sm">Editar</a>
  			<a href="{% url 'tarea:eliminar_lista' lista.id %}" class="btn btn-danger btn-sm">Eliminar</a>
  			</div>
  			</form>
		</div>
           
        {% endfor %}
        
    {% else %}
        <p>No hay listas creadas</p>
    {% endif %}

{% endblock %}
</div>

tarea/templates/tarea/lista_delete.html
{% extends 'base.html' %}

{% block container %}
	<form method="post">
		{%csrf_token %}
		<div class="container">
		<h3>¿Desea eliminar el registro de {{ object.titulo_lista}}?</h3>
		<button class="btn btn-danger" type="submit">Si, eliminar</button>
		<a class= "btn btn-default" href="{% url 'tarea:clase_index' %}">Cancelar</a>
		</div>
	</form>
		}
		

{% endblock %}

tarea/templates/tarea/lista_detail.html
{% extends 'base.html' %}

{% block container %}
	<div class="container">
	{% for tarea in lista.tarea_set.all %}

	<div class="jumbotron">
  			<h1><a href=#>{{ tarea.titulo_tarea }}</a> </h1>
        <h3>{{ tarea.descripcion }} </h3>
        <h4>Lista: {{ tarea.lista }} </h4>
        {% if tarea.terminado %}
       <a href="{% url 'tarea:desmarcar_tarea' lista.id %}?tarea={{tarea.id}}">Desmarcar como finalizada</a>
        {% else %}
         <a href="{% url 'tarea:marcar_tarea' lista.id %}?tarea={{tarea.id}}">Finalizar</a>
         {% endif %}
       	<h5>Creacion: {{ tarea.fecha_creacion_tarea }} | Ultima modificación: {{ tarea.fecha_modificacion }}</h5>
       
		</div>
           
        {% endfor %}
</div>
{% endblock %}

tarea/templates/tarea/lista_form.html
{%  extends 'base.html' %}



{% block container %}
<div class="container">
	<form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Guardar" class="btn btn-primary">
		
	</form>
{% endblock %}
</div>

tarea/templates/tarea/tarea_delete.html
{% extends 'base.html' %}

{% block container %}
	<form method="post">
		{%csrf_token %}
		<div class="container">
		<h3>¿Desea eliminar el registro de {{ object.titulo_tarea}}?</h3>
		<button class="btn btn-danger" type="submit">Si, eliminar</button>
		<a class= "btn btn-default" href="{% url 'tarea:clase_tarea' %}">Cancelar</a>
		</div>
	</form>
		}
		

{% endblock %}

tarea/templates/tarea/tarea_form.html
{%  extends 'base.html' %}



{% block container %}
<div class="container">
	<form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Guardar" class="btn btn-primary">
		
	</form>
{% endblock %}
</div>

tarea/templates/tarea/tarea_index.html
{% extends 'base.html' %}


{% block container %}

<div class= "container">
<a href="{% url 'tarea:crear_tarea' %}" class="btn btn-default btn-lg btn-block">Crear Tarea</a>

{% if object_list %}
	 
        {% for tarea in object_list %}

        <div class="jumbotron">
  			<h1><a href=#>{{ tarea.titulo_tarea }}</a> </h1>
        <h3>{{ tarea.descripcion }} </h3>
        <h4>Lista: {{ tarea.lista }} </h4>
         {%if tarea.terminado == True%}
        <h4 class="text-danger">Finalizada</h4>
        {% else %}
        <h4 class="text-warning">En ejecución</h4>
        {% endif %}
       	<h5>Creacion: {{ tarea.fecha_creacion_tarea }} | Ultima modificación: {{ tarea.fecha_modificacion }}</h5>
        
        
  			
  			<div class="d-inline">

  			<form method="post">
  			{% csrf_token %}

  			<a href="{% url 'tarea:modificar_tarea' tarea.id %}" class="btn btn-primary btn-sm">Editar</a>
  			<a href="{% url 'tarea:eliminar_tarea' tarea.id %}" class="btn btn-danger btn-sm">Eliminar</a>
  			</div>
  			</form>
		</div>
           
        {% endfor %}
        
    {% else %}
        <p>No hay tareas</p>
    {% endif %}

{% endblock %}
</div>

tarea/templates/tarea/tareas_pendientes.html
{% extends 'base.html' %}

{% block container %}
<div class="container">

{% if object_list %}
	 
        {% for tarea in object_list %}

        <div class="jumbotron">
  			<h1><a href=#>{{ tarea.titulo_tarea }}</a> </h1>
        <h3>{{ tarea.descripcion }} </h3>
        <h4>Lista: {{ tarea.lista }} </h4>
        {%if tarea.terminado == True%}
        <h4 class="text-danger">Finalizada</h4>
        {% else %}
        <h4 class="text-warning">En ejecución</h4>
        {% endif %}
       	<h5>Creacion: {{ tarea.fecha_creacion_tarea }} | Ultima modificación: {{ tarea.fecha_modificacion }}</h5>
       
		</div>
           
        {% endfor %}
        
    {% else %}
        <p>N hay tareas</p>
    {% endif %}
	
{% endblock %}
</div>

tarea/templates/tarea/tareas_pendientes_mes.html
{% extends 'base.html' %}

{% block container %}
<div class="container">

{% if object_list %}
	 
        {% for tarea in object_list %}

        <div class="jumbotron" >
  			<h1><a href=#>{{ tarea.titulo_tarea }}</a> </h1>
        <h3>{{ tarea.descripcion }} </h3>
        <h4>Lista: {{ tarea.lista }} </h4>
        {%if tarea.terminado == True%}
        <h4 class="text-danger">Finalizada</h4>
        {% else %}
        <h4 class="text-warning">En ejecución</h4>
        {% endif %}
       	<h5>Creacion: {{ tarea.fecha_creacion_tarea }} | Ultima modificación: {{ tarea.fecha_modificacion }} </h5>
        
        </div>
  			
  			
           
        {% endfor %}
        
    {% else %}
        <p>No hay tareas.</p>
    {% endif %}
	
{% endblock %}
</div>

tarea/templates/tarea/tareas_terminadas.html
{% extends 'base.html' %}


{% block container %}

<div class= "container">
<a href="{% url 'tarea:crear_tarea' %}" class="btn btn-default btn-lg btn-block">Crear Tarea</a>

{% if object_list %}
   
        {% for tarea in object_list %}

        <div class="jumbotron">
        <h1><a href=#>{{ tarea.titulo_tarea }}</a> </h1>
        <h3>{{ tarea.descripcion }} </h3>
        <h4>Lista: {{ tarea.lista }} </h4>
        {%if tarea.terminado == True%}
        <h4 class="text-danger">Finalizada</h4>
        {% else %}
        <h4 class="text-warning">En ejecución</h4>
        {% endif %}
        <h5>Creacion: {{ tarea.fecha_creacion_tarea }} | Ultima modificación: {{ tarea.fecha_modificacion }} </h5>
      
    </div>
           
        {% endfor %}
        
    {% else %}
        <p>No hay tareas</p>
    {% endif %}

{% endblock %}
</div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    

    <title>{% block title %} Listas de tarea {% endblock %}</title>

   
    <link href="{% static 'css/bootstrap_tema.min.css' %}" rel="stylesheet">
    

    

  </head>

  <body>


    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=#">Lista de Tareas</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="{% if active_title == 'lista' %}active{% endif %}"><a href="{% url 'tarea:clase_index' %}">Listas <span class="sr-only">(current)</span></a></li>
        <li class="{% if active_title == 'tarea' %}active{% endif %}"><a href="{% url 'tarea:clase_tarea' %}">Tareas</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reportes <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'tarea:tareas_pendientes' %}">Tareas pendientes</a></li>
            <li><a href="{% url 'tarea:tareas_terminadas' %}">Tareas terminadas en el mes actual</a></li>
            <li><a href="{% url 'tarea:tareas_pendientes_mes' %}">Tareas pendientes hace mas de un mes</a></li>
           
          </ul>
        </li>
      </ul>
    
    </div>
  </div>
</nav>
<div class="container">
{% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{% if message.tags == 'error' %}danger{% else%}{{ message.tags }}{% endif %} alert-dismissible"{% endif %} role='alert'>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}

        </div>

        {% block container %}
     
        

  
        {% endblock container %}


    {% block extra_footer %}

    {% endblock extra_footer %}
    
        
        <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
    





  </body>
</html>